name: Matrix configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, windows-latest]
        images: [hello-world, alpine]
        exclude:
          - os: windows-latest
            images: alpine
        include:
          - os: ubuntu-24.04
            images: amd64/alpine
    runs-on: ${{ matrix.os }}
    steps:
      - name: echo docker details
        run: docker info

      - name: run image on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}
   

  #deploy-on-windows:
   # runs-on: windows-latest
    #steps:
     # - name: echo docker details
      #  run: docker info

      #- name: run image
       # run: docker run hello-world


    