name: my first workflow

on: push

jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: List and Read
              run: |
                echo "my first workflow on Github Action job"
                ls -ltra
                cat README.md
            
            - name: Install Cowsay Program
              run: sudo apt-get install cowsay -y
            
            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt 

             