name: Exploring Variable and Secrets

on:
    push

env:
    CONTAINER_REGISTRY: docker.io  # Default value for container registry
    IMAGE_NAME: my-app            # Default value for image name

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest .

            - name: Docker Login
              run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
            
            - name: Docker Publish
              run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        
    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps: 
            - name: Docker Run
              run: docker run -d -p 8080:80 docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

