name: Exploring Variable and Secrets

on:
    push

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: Docker build -t ${{ env.CONTAINER_REGISTRY}}/$DOCKER_USERNAME/$IMAGE_NAME:latest

            - name: Docker login
              run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
            
            - name: Docker Publish
              run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
        
        deploy:
            needs: docker
            run-on: ubuntu-lates
            steps: 
                - name: Docker Run
                  docker run -d  -p 8080:80 docker.io/dockerUsername/imageName:latest
